-- GENERATED by render_replay.py from CONCORDANCE.json. Do not hand-edit: the point of
-- generating it is that the declarations checked here CANNOT drift from the ones the
-- edition's record claims. Same shape as engine/release_verify.sh's Verify.lean, which
-- is the programme's actual certifier.
--
-- A PASS is: every line below prints exactly
--     'depends on axioms: [propext, Classical.choice, Quot.sound]'
-- Any sorryAx, or any axiom outside that triple, is a FAILURE — and it is a failure
-- even if the build succeeded, which is the whole reason this file exists.

import Sandbox.A1.GL1.GOALv0a
import Sandbox.A1.GL1.PresentedU
import Sandbox.A1.GL1.FamilyField1
import Sandbox.A1.GL1.NewtonUnivGrid
import Sandbox.A1.GL1.NewtonUnivSpan
import Sandbox.A1.GL1.NonDegeneracy
import Sandbox.A1.GL1.KzBridge

#print axioms HybridQuantumLean.A1.GL1Newton.clause_i
#print axioms HybridQuantumLean.A1.GL1Newton.clause_i_ambient
#print axioms HybridQuantumLean.A1.GL1Newton.clause_i_in_torus
#print axioms HybridQuantumLean.A1.GL1Newton.KzBridge.clause_i_Kz
#print axioms HybridQuantumLean.A1.GL1Newton.clause_ii
#print axioms HybridQuantumLean.A1.GL1Newton.clause_ii_ambient
#print axioms HybridQuantumLean.A1.GL1Newton.ZUev_eq_ZUevAmbient
#print axioms HybridQuantumLean.A1.GL1Newton.Nev_eq_span
#print axioms HybridQuantumLean.A1.GL1Newton.Newton_iff_mem_span
#print axioms HybridQuantumLean.A1.GL1Newton.mem_span_of_Newton
#print axioms HybridQuantumLean.A1.GL1Newton.clause_iii
#print axioms HybridQuantumLean.A1.GL1Newton.KzBridge.clause_iii_Kz
#print axioms HybridQuantumLean.A1.GL1Newton.Az_nuGrid
#print axioms HybridQuantumLean.A1.GL1Newton.Newton_nuGen
#print axioms HybridQuantumLean.A1.GL1Newton.Newton_of_mem_span
#print axioms HybridQuantumLean.A1.GL1Newton.expand
#print axioms HybridQuantumLean.A1.GL1Newton.expand_spec
#print axioms HybridQuantumLean.A1.GL1Newton.expand_witnesses_span
#print axioms HybridQuantumLean.A1.GL1Newton.Presentation.equivTorus
#print axioms HybridQuantumLean.A1.GL1Newton.Presentation.uBasis
#print axioms HybridQuantumLean.A1.GL1Newton.Presentation.existsUnique_lift
#print axioms HybridQuantumLean.A1.GL1Newton.Presentation.modelEquiv
#print axioms HybridQuantumLean.A1.GL1Newton.clause_iii_nondegenerate
#print axioms HybridQuantumLean.A1.GL1Newton.trap4_separator
#print axioms HybridQuantumLean.A1.GL1Newton.FamilyField1.Qsub_one_inv_not_mem
#print axioms HybridQuantumLean.A1.GL1Newton.Newton_ssubset_univ
#print axioms HybridQuantumLean.A1.GL1Newton.nuGenSpan_ne_top
#print axioms HybridQuantumLean.A1.GL1Newton.Laurent_ssubset_Newton
#print axioms HybridQuantumLean.A1.GL1Newton.KzBridge.Newton_mem_KzAmbient
#print axioms HybridQuantumLean.A1.GL1Newton.KzBridge.nuGenSet_subset_KzAmbient
#print axioms HybridQuantumLean.A1.GL1Newton.KzBridge.mem_UevKz_iff_Newton
