import Sandbox.A1.GL1.GOALv0a
import Mathlib.Algebra.Field.Subfield.Basic
import Mathlib.Algebra.MonoidAlgebra.MapDomain

set_option linter.style.header false
set_option linter.unusedSectionVars false

/-!
# `A1.GL1Newton.KzBridge` — the literal `K_z`-ambient clauses (kills panel finding F-K1)

Binding statement of record: `sandboxv0a/informal/goalv0a.lock.json` (tex `91a50173…5a7e`).
Panel record: `sandboxv0a/cow/COW_FAITHFULNESS_PANEL.md`, finding **F-K1**, disposition **(b)**.

## What this module does

The certified `goalv0a` bundle (`GOALv0a.lean`) lives over the concrete family field
`K₁ = Frac(ℤ[q^±,z^±]) = ℚ(q,z)`.  The signed goal instead fixes the *ring*
`K_z = ℚ(q)[z^{±1}] ⊊ K₁` as the coefficient ring of the toral algebra
`U = K_z[(T⁺)^{±1}]`, hence of the even frame `K_z[Y̌^{±1}]`.  The three-seat CoW panel ruled
this an object substitution (F-K1, 2:1).  This module closes F-K1 **by proof** (fable seat's
finding-2 route): it defines the `K_z`-submodel inside `Frame K₁` and certifies the literal
`K_z`-ambient clauses as corollaries of the existing `K₁` theorems.  Nothing here weakens or
re-states any pinned theorem; the six existing GL1 modules are untouched.

## The design (target 1) — no property smuggling

The `K_z`-subring of `K₁` is realized in two raw layers:

* `Fq := Subfield.closure {qK}` — the subfield `ℚ(q) ⊆ K₁`.  As a subfield of a characteristic-0
  field it automatically contains the prime field `ℚ`, so `Fq = ℚ(q)` exactly.
* `KzCoeff := Subring.closure (↑Fq ∪ {zK, zK⁻¹})` — the subring generated by `ℚ(q)` together with
  `z^{±1}`, i.e. `K_z = ℚ(q)[z^{±1}]` verbatim.

`KzAmbient` is then defined as the **range of the coefficient-inclusion ring map** on Laurent
polynomials, `kzMap := AddMonoidAlgebra.mapRingHom ℤ KzCoeff.subtype`, so it is a bona fide
`Subring (Frame K₁)` with no properties assumed.  The characterizing property — that its members
are exactly the Laurent polynomials in `Y̌` whose coefficients lie in `K_z` — is proved as the
theorem `mem_KzAmbient_iff`.  This is the Lean realization of `K_z[Y̌^{±1}]`.

## The clauses

* `nuGenSet_subset_KzAmbient` (target 2) — every generator `Y̌^u ν_r(Y̌)` lies in `KzAmbient`,
  because `ν_r` has `ℚ(q)`-coefficients.
* `Newton_mem_KzAmbient` (target 3, **the F-K1 killer**) — every `t` with `Newton t` lies in
  `KzAmbient`: the `K₁`-Newton lattice coincides with the `K_z`-Newton lattice.  Route:
  `Newton t → t ∈ span_{A_z} nuGenSet` (`mem_span_of_Newton`) → span of `KzAmbient`-generators with
  `A_z ⊆ K_z` coefficients stays in `KzAmbient`.
* `clause_iii_Kz` (target 4) — clause (iii) restricted to `KzAmbient` (the literal informal clause).
* `clause_i_Kz` (target 5) — the Newton elements of `KzAmbient` form an `A_z`-subalgebra `UevKz`.

## Clause (ii) has no separate `K_z` form (recorded, not forced)

`goalv0a` Def 3 defines the centre as `Z(U^ev) = U^ev ∩ Z(U ⊗_{K_z} Frac(A_z))`.  The centre is
taken **after base change to `Frac(A_z)`**, and `Frac(A_z) = Frac(ℤ[q^±,z^±]) = ℚ(q,z) = K₁`
(`FamilyField1`, module docstring).  So the ambient of the centre object is intrinsically `K₁`, not
`K_z`: there is no `K_z`-restriction of clause (ii) to make — the base change already lands in `K₁`.
This is the panel fable seat's reading, unanimously graded FAITHFUL across both passes for Def 3.
Accordingly clause (ii) is certified only in its `K₁` form (`GOALv0a.clause_ii{,_ambient}`); the
present module adds nothing for it, by design.

## Status

Complete and `sorry`-free.  Every declaration is a corollary of the certified `K₁` development;
no CAS obligation and no new mathematical content is introduced.
-/

open BigOperators

namespace HybridQuantumLean
namespace A1
namespace GL1Newton
namespace KzBridge

open HybridQuantumLean.A1.Verma
open HybridQuantumLean.A1.Verma.GL2
open LaurentPolynomial
open FamilyField1

/-! ## 1. The `K_z` coefficient subring `K_z = ℚ(q)[z^{±1}] ⊆ K₁` -/

/-- **`Fq = ℚ(q) ⊆ K₁`** — the subfield generated by `q`.  In characteristic 0 it contains the
prime field `ℚ`, so it is exactly `ℚ(q)`. -/
noncomputable def Fq : Subfield K1 := Subfield.closure {qK}

/-- `q ∈ ℚ(q)`. -/
theorem qK_mem_Fq : qK ∈ Fq := Subfield.subset_closure (Set.mem_singleton _)

/-- `(Q^t) = (q²)^t ∈ ℚ(q)` for every natural `t` (the unshifted grid points). -/
theorem Qpow_mem_Fq (t : ℕ) : (qK ^ 2) ^ t ∈ Fq := pow_mem (pow_mem qK_mem_Fq 2) t

/-- **`K_z = ℚ(q)[z^{±1}] ⊆ K₁`** — the subring generated by `ℚ(q)` together with `z` and `z⁻¹`. -/
noncomputable def KzCoeff : Subring K1 := Subring.closure ((Fq : Set K1) ∪ {zK, zK⁻¹})

/-- `ℚ(q) ⊆ K_z`. -/
theorem mem_KzCoeff_of_mem_Fq {x : K1} (hx : x ∈ Fq) : x ∈ KzCoeff :=
  Subring.subset_closure (Set.mem_union_left _ hx)

/-- `z ∈ K_z`. -/
theorem zK_mem_KzCoeff : zK ∈ KzCoeff :=
  Subring.subset_closure (Set.mem_union_right _ (Set.mem_insert _ _))

/-- `z⁻¹ ∈ K_z`. -/
theorem zK_inv_mem_KzCoeff : zK⁻¹ ∈ KzCoeff :=
  Subring.subset_closure (Set.mem_union_right _ (Set.mem_insert_of_mem _ rfl))

/-- **`A_z ⊆ K_z`** — the coefficient subring `A_z = ℤ[q^±,z^±]` sits inside `K_z = ℚ(q)[z^±]`.
This is the ring-theoretic content that makes the two Newton lattices coincide. -/
theorem AzSubring_le_KzCoeff : AzSubring (K := K1) ≤ KzCoeff := by
  rw [AzSubring, Subring.closure_le]
  intro y hy
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hy
  rcases hy with rfl | rfl | rfl | rfl | rfl | rfl
  · exact mem_KzCoeff_of_mem_Fq qK_mem_Fq
  · exact mem_KzCoeff_of_mem_Fq (Fq.inv_mem qK_mem_Fq)
  · exact zK_mem_KzCoeff
  · exact zK_inv_mem_KzCoeff
  · exact one_mem _
  · exact (show ((1 : K1))⁻¹ ∈ KzCoeff by rw [inv_one]; exact one_mem _)

/-! ## 2. `KzAmbient = K_z[Y̌^{±1}] ⊆ Frame K₁` as the range of the coefficient map -/

/-- The coefficient-inclusion ring map `K_z[Y̌^{±1}] → K₁[Y̌^{±1}]` induced by `K_z ↪ K₁`. -/
noncomputable def kzMap : LaurentPolynomial (↥KzCoeff) →+* Frame K1 :=
  AddMonoidAlgebra.mapRingHom ℤ KzCoeff.subtype

/-- `kzMap` acts coefficientwise: the `u`-th coefficient of `kzMap x` is `↑(x u)`. -/
theorem kzMap_apply (x : LaurentPolynomial (↥KzCoeff)) (u : ℤ) :
    kzMap x u = (x u : K1) :=
  AddMonoidAlgebra.mapRingHom_apply _ _ _

/-- **`KzAmbient = K_z[Y̌^{±1}]`** — the `K_z`-submodel of `Frame K₁`, as a `Subring`.  Its members
are characterized by `mem_KzAmbient_iff` as exactly the Laurent polynomials in `Y̌` with
coefficients in `K_z`. -/
noncomputable def KzAmbient : Subring (Frame K1) := kzMap.range

/-- **The characterizing property (no smuggling)** — `f ∈ KzAmbient` iff every Laurent coefficient
of `f` lies in `K_z`.  This is the Lean realization of `K_z[Y̌^{±1}]`. -/
theorem mem_KzAmbient_iff (f : Frame K1) : f ∈ KzAmbient ↔ ∀ u : ℤ, f u ∈ KzCoeff := by
  constructor
  · rintro ⟨x, rfl⟩ u
    rw [kzMap_apply]
    exact (x u).2
  · intro h
    classical
    refine ⟨Finsupp.mapRange (fun a => if ha : a ∈ KzCoeff then (⟨a, ha⟩ : ↥KzCoeff) else 0)
      (by dsimp only; rw [dif_pos (zero_mem KzCoeff)]; exact Subtype.ext rfl) f, ?_⟩
    ext u
    rw [kzMap_apply, Finsupp.mapRange_apply, dif_pos (h u)]

/-- `C s ∈ KzAmbient` whenever the scalar `s` lies in `K_z`. -/
theorem C_mem {s : K1} (hs : s ∈ KzCoeff) : (C s : Frame K1) ∈ KzAmbient := by
  refine RingHom.mem_range.mpr ⟨C (⟨s, hs⟩ : ↥KzCoeff), ?_⟩
  ext u
  rw [kzMap_apply, LaurentPolynomial.C_apply, LaurentPolynomial.C_apply]
  split_ifs <;> rfl

/-- `T n ∈ KzAmbient` for every `n` (the monomials have coefficient `1 ∈ K_z`). -/
theorem T_mem (n : ℤ) : (T n : Frame K1) ∈ KzAmbient := by
  refine RingHom.mem_range.mpr ⟨T n, ?_⟩
  ext u
  rw [kzMap_apply, LaurentPolynomial.T_apply, LaurentPolynomial.T_apply]
  split_ifs <;> rfl

/-- `K_z`-scalar closure of `KzAmbient` (the `•`-form used by `Submodule.span_induction`). -/
theorem KzAmbient_smul {c : K1} (hc : c ∈ KzCoeff) {x : Frame K1} (hx : x ∈ KzAmbient) :
    c • x ∈ KzAmbient := by
  rw [LaurentPolynomial.smul_eq_C_mul]
  exact KzAmbient.mul_mem (C_mem hc) hx

/-! ## 3. The generators lie in `KzAmbient` (target 2) -/

/-- `ν_r(Y̌) = toLaurent(ν_r)` lies in `KzAmbient`: `ν_r = ∏_{t<r}(X−Q^t)/(Q^r−Q^t)` is a product of
factors with `ℚ(q) ⊆ K_z` coefficients. -/
theorem toLaurent_nu_mem (r : ℕ) :
    (Polynomial.toLaurent (nu (G := instGL2ParamsK1) r)) ∈ KzAmbient := by
  rw [nu, newtonPolyK, map_prod]
  refine Subring.prod_mem _ fun t _ => ?_
  rw [map_mul, map_sub, map_mul, Polynomial.toLaurent_C, Polynomial.toLaurent_C,
    Polynomial.toLaurent_C, Polynomial.toLaurent_X]
  refine KzAmbient.mul_mem (KzAmbient.sub_mem (KzAmbient.mul_mem ?_ ?_) ?_) ?_
  · exact C_mem (one_mem _)
  · exact T_mem 1
  · exact C_mem (mem_KzCoeff_of_mem_Fq (Qpow_mem_Fq t))
  · exact C_mem (mem_KzCoeff_of_mem_Fq
      (Fq.inv_mem (Subring.sub_mem _ (Qpow_mem_Fq r) (Qpow_mem_Fq t))))

/-- **Every generator `Y̌^u ν_r(Y̌)` lies in `KzAmbient`.** -/
theorem nuGen_mem (u : ℤ) (r : ℕ) :
    nuGen (G := instGL2ParamsK1) u r ∈ KzAmbient := by
  rw [nuGen]
  exact KzAmbient.mul_mem (T_mem u) (toLaurent_nu_mem r)

/-- **Target 2** — the clause-(iii) generating set lies inside `KzAmbient`. -/
theorem nuGenSet_subset_KzAmbient :
    (nuGenSet (G := instGL2ParamsK1)) ⊆ (KzAmbient : Set (Frame K1)) := by
  rintro p ⟨u, r, rfl⟩
  exact nuGen_mem u r

/-! ## 4. The Newton lattice lands in `KzAmbient` (target 3 — kills F-K1) -/

/-- **Target 3 — the F-K1 killer.**  Every `t` with `Newton t` (grid-integrality over `A_z`) lies
in `KzAmbient = K_z[Y̌^{±1}]`.  Hence the `K₁`-Newton lattice `𝒩^ev` coincides with the `K_z`-Newton
lattice: enlarging the coefficient field from `K_z` to `K₁` adds no new Newton elements. -/
theorem Newton_mem_KzAmbient {t : Frame K1} (ht : Newton (G := instGL2ParamsK1) t) :
    t ∈ KzAmbient := by
  have hspan := mem_span_of_Newton (G := instGL2ParamsK1) ht
  refine Submodule.span_induction ?_ ?_ ?_ ?_ hspan
  · intro p hp
    exact nuGenSet_subset_KzAmbient hp
  · exact KzAmbient.zero_mem
  · intro x y _ _ hx hy
    exact KzAmbient.add_mem hx hy
  · intro c x _ hx
    exact KzAmbient_smul (AzSubring_le_KzCoeff c.2) hx

/-! ## 5. The literal `K_z`-ambient clauses (iii) and (i) -/

/-- **Target 4 — clause (iii) over `K_z`.**  For `t ∈ KzAmbient = K_z[Y̌^{±1}]`,
`t ∈ 𝒩^ev ↔ t ∈ Σ_{u∈ℤ} Σ_{r≥0} A_z · Y̌^u ν_r(Y̌)`.  This is the literal informal clause (iii),
now certified with the coefficient ring `K_z` rather than `K₁`.  (It holds for every `t`; the
`KzAmbient` hypothesis records that we are reading it inside the intended `K_z`-model.) -/
theorem clause_iii_Kz {t : Frame K1} (_ht : t ∈ KzAmbient) :
    Newton (G := instGL2ParamsK1) t ↔
      t ∈ Submodule.span (AzSubring (K := K1)) (nuGenSet (G := instGL2ParamsK1)) :=
  clause_iii t

/-- **The Newton elements of `KzAmbient`** as an `A_z`-subalgebra of `Frame K₁`.  This is the
restriction of `UevSubalg = 𝒩^ev` to the `K_z`-model `KzAmbient`. -/
noncomputable def UevKz : Subalgebra (↥(AzSubring (K := K1))) (Frame K1) where
  carrier := {t | Newton (G := instGL2ParamsK1) t ∧ t ∈ KzAmbient}
  mul_mem' := fun hf hg => ⟨Newton_mul hf.1 hg.1, KzAmbient.mul_mem hf.2 hg.2⟩
  add_mem' := fun hf hg => ⟨Newton_add hf.1 hg.1, KzAmbient.add_mem hf.2 hg.2⟩
  algebraMap_mem' := fun r => by
    refine ⟨Newton_algebraMap r, ?_⟩
    have h : algebraMap (↥(AzSubring (K := K1))) (Frame K1) r = C (r : K1) := rfl
    rw [h]
    exact C_mem (AzSubring_le_KzCoeff r.2)
  zero_mem' := ⟨Newton_zero, KzAmbient.zero_mem⟩
  one_mem' := ⟨Newton_one, KzAmbient.one_mem⟩

/-- **Target 5 — clause (i) over `K_z`.**  The even Newton elements that live in the `K_z`-model
`KzAmbient` form an `A_z`-subalgebra `UevKz` of `Frame K₁`; membership is exactly
`Newton t ∧ t ∈ K_z[Y̌^{±1}]`.  Together with `Newton_mem_KzAmbient` (target 3) the second conjunct
is automatic, so `UevKz` has the same underlying set as `𝒩^ev = UevSubalg`. -/
theorem clause_i_Kz (t : Frame K1) :
    t ∈ UevKz ↔ (Newton (G := instGL2ParamsK1) t ∧ t ∈ KzAmbient) := Iff.rfl

/-- The `K_z`-model captures the whole Newton lattice: `UevKz` and `UevSubalg` cut out the same
elements of `Frame K₁` (the second conjunct of `clause_i_Kz` is implied by the first, target 3). -/
theorem mem_UevKz_iff_Newton (t : Frame K1) :
    t ∈ UevKz ↔ Newton (G := instGL2ParamsK1) t :=
  ⟨fun h => h.1, fun h => ⟨h, Newton_mem_KzAmbient h⟩⟩

end KzBridge
end GL1Newton
end A1
end HybridQuantumLean
