import Sandbox.A1.GL1.NewtonUnivGrid

set_option linter.style.header false
set_option linter.unusedSectionVars false

/-!
# `A1.GL1Newton.NewtonUnivSpan` — clause (iii): the `ν`-presentation of `𝒩^ev`

Binding statement of record: `sandboxv0a/informal/goalv0a.lock.json` clause (iii)
(tex `91a50173…5a7e`).  Binding informal proof: `sandboxv0a/informal/PROOFv0a.tex` §"Clause (iii)".

## The statement

`goalv0a` clause (iii):

  `𝒩^ev = Σ_{u ∈ ℤ} Σ_{r ≥ 0} A_z · Y̌^u ν_r(Y̌)`.

The right-hand side is the `A_z`-submodule generated by `nuGenSet = { Y̌^u ν_r(Y̌) }`; the
left-hand side is the grid predicate `Newton`.  `Newton_iff_mem_span` is the equality, and
`Nev_eq_span` is its literal set form.

## Content and prior art

This is the one substantive clause: the **bilateral quantum Pólya theorem** of Harman–Hopkins
(*Quantum integer-valued polynomials*, arXiv:1601.06110, §1 Prop. + §4 localization Prop.), on the
multiplicative grid `Y̌ = Q^χ`, with `z` a spectator.  It is NOT in Mathlib (no integer-valued
polynomial theory, no Gaussian binomials).  The two-variable analogue is already kernel-certified
in this program: `Sandbox/A1/UQ/NewtonSpan.lean:298` (`nuNewtonIntegral_iff_mem_span`); its proof is
the model for M2 (Fin 2 → one Laurent variable: **fewer** moving parts — no `span_mul_span`, no
product family).

Proof shape (`PROOFv0a` §3): `⟸` = generator integrality (`Newton_nuGen`) + `span_induction`;
`⟹` = Laurent clearing `t = Y̌^{-N}·g` with `g` polynomial, the triangular basis
`CenterNewtonZ.X_pow_mem_span_newtonPolyK` (at `a = 1`), and coefficient pinning by
`CenterLattice.gridCriterion` on the window `χ = 0,…,d`.

## Status (M2, revised wave 3)

Complete and `sorry`-free.  Both legs are proved: `Newton_of_mem_span` (`⟸`, generator
integrality + `Submodule.span_induction`) and `mem_span_of_Newton` (`⟹`, Laurent clearing +
windowed unitriangular pinning through `CenterLattice.coeff_mem_of_grid_mem`).

Wave 3 (verification finding F5): the Newton coordinate map mandated by the naming concordance
(`GL1Newton.expand`, notes §3 `c_r`) is now a real definition rather than an anonymous local, and
`expand_witnesses_span` proves that the coordinates it returns are exactly the ones witnessing
clause (iii).  `mem_span_of_Newton` is unchanged as a statement and now consumes it.
-/

open BigOperators

namespace HybridQuantumLean
namespace A1
namespace GL1Newton

open HybridQuantumLean.A1.Verma
open HybridQuantumLean.A1.Verma.GL2
open LaurentPolynomial

universe u

variable {K : Type u} [Field K] [G : GL2Params K]

/-- **The `⟸` leg.**  `Σ_u Σ_r A_z Y̌^u ν_r(Y̌) ⊆ 𝒩^ev` (`PROOFv0a` Lemma 2): every generator
is grid-integral and `Newton` is closed under `A_z`-combinations. -/
theorem Newton_of_mem_span [QGeneric K] {t : Frame K}
    (ht : t ∈ Submodule.span (AzSubring (K := K)) (nuGenSet (G := G))) :
    Newton (G := G) t := by
  refine Submodule.span_induction ?_ ?_ ?_ ?_ ht
  · rintro p ⟨u, r, rfl⟩
    exact Newton_nuGen u r
  · exact Newton_zero
  · intro x y _ _ hx hy
    exact Newton_add hx hy
  · intro c x _ hx
    exact Newton_smul c.2 hx

/-! ### The univariate triangular basis at the unshifted linear coefficient `a = 1` -/

/-- `X^i` lies in the `K`-span of `ν_0, …, ν_i` — the certified triangular basis
`CenterNewtonZ.X_pow_mem_span_newtonPolyK` at `a = 1` (`nu r = newtonPolyK 1 r`). -/
theorem X_pow_mem_span_nu [QGeneric K] (i : ℕ) :
    (Polynomial.X : Polynomial K) ^ i
      ∈ Submodule.span K ((fun r => nu (G := G) r) '' ↑(Finset.range (i + 1))) :=
  X_pow_mem_span_newtonPolyK (G := G) (1 : K) one_ne_zero i

/-- Monotonicity of the triangular basis window: `X^i ∈ span_K {ν_r : r ≤ d}` for `i ≤ d`. -/
theorem X_pow_mem_span_nu_le [QGeneric K] {i d : ℕ} (h : i ≤ d) :
    (Polynomial.X : Polynomial K) ^ i
      ∈ Submodule.span K ((fun r => nu (G := G) r) '' ↑(Finset.range (d + 1))) := by
  refine Submodule.span_mono (Set.image_mono ?_) (X_pow_mem_span_nu (G := G) i)
  intro x hx
  simp only [Finset.coe_range, Set.mem_Iio] at hx ⊢
  omega

/-! ### The Newton coordinate map `expand` (naming concordance §3, `c_r`)

`translate/v0aprep/v0a_newton_functions.jl` mandates a Lean object `GL1Newton.expand f` — the
Newton coordinate map `c_r` of the notes §3, i.e. the coefficients of `f` in the basis
`ν_0, ν_1, …`.  It is defined here by the same triangular sweep the Julia spec uses, but taken
on the **grid** rather than on leading coefficients: since `ν_r(Q^m) = 0` for `m < r` and
`ν_m(Q^m) = 1` (`CenterNewton.nuNewton_eval_zero_of_lt`, `nuNewton_eval_self`), the evaluation
matrix is lower unitriangular and the coordinates are recovered by

  `c_m = f(Q^m) − Σ_{r<m} c_r · ν_r(Q^m)`.

`expand_spec` proves that these really are the Newton coordinates (`Σ_{r ≤ d} c_r ν_r = f` for
`deg f ≤ d`), and `expand_witnesses_span` proves that they are the very coordinates that witness
clause (iii): they lie in `A_z` and reassemble `t`. -/

/-- **`GL1Newton.expand p`** — the Newton coordinate map `c : ℕ → K` of a polynomial `p`,
`c_m = p(Q^m) − Σ_{r<m} c_r ν_r(Q^m)` (the unitriangular grid sweep). -/
noncomputable def expand (p : Polynomial K) (m : ℕ) : K :=
  m.strongRecOn' fun n ih =>
    Polynomial.eval ((G.q ^ 2 : K) ^ n) p
      - ∑ r ∈ (Finset.range n).attach,
          ih r.1 (Finset.mem_range.mp r.2) * nuGrid (G := G) r.1 (n : ℤ)

/-- The defining recursion of `expand`, with the sum taken over `Finset.range m`. -/
theorem expand_def (p : Polynomial K) (m : ℕ) :
    expand (G := G) p m = Polynomial.eval ((G.q ^ 2 : K) ^ m) p
      - ∑ r ∈ Finset.range m, expand (G := G) p r * nuGrid (G := G) r (m : ℤ) := by
  rw [expand, Nat.strongRecOn'_beta]
  congr 1
  rw [← Finset.sum_attach (Finset.range m)
    (fun r => expand (G := G) p r * nuGrid (G := G) r (m : ℤ))]
  rfl

/-- **Uniqueness of the Newton coordinates.**  Any `K`-coordinate family realising `p` in the
window `ν_0, …, ν_d` agrees with `expand p` there.  (Strong induction on `m`, using the
unitriangular grid evaluation `CenterLattice.newtonSum_eval_grid`.) -/
theorem expand_eq_of_span [QGeneric K] {d : ℕ} {p : Polynomial K} {c : ℕ → K}
    (hc : (∑ r ∈ Finset.range (d + 1), c r • nu (G := G) r) = p) :
    ∀ m ≤ d, expand (G := G) p m = c m := by
  intro m
  induction m using Nat.strong_induction_on with
  | _ m ih =>
    intro hmd
    have hev : Polynomial.eval ((G.q ^ 2 : K) ^ m) p
        = newtonSum (K := K) d c ((G.q ^ 2) ^ m) := by
      rw [← hc, Polynomial.eval_finsetSum]
      unfold newtonSum
      refine Finset.sum_congr rfl fun r _ => ?_
      rw [Polynomial.smul_eq_C_mul, Polynomial.eval_mul, Polynomial.eval_C, eval_nu]
    have hterm : ∀ r ∈ Finset.range m,
        expand (G := G) p r * nuGrid (G := G) r (m : ℤ)
          = c r * nuNewton (K := K) r ((G.q ^ 2) ^ m) := by
      intro r hr
      have hrm : r < m := Finset.mem_range.mp hr
      rw [ih r hrm (le_trans hrm.le hmd)]
      congr 1
      unfold nuGrid
      rw [zpow_natCast]
    rw [expand_def, hev, newtonSum_eval_grid d c hmd, Finset.sum_congr rfl hterm]
    ring

/-- **`expand` really is the Newton expansion**: `p = Σ_{r ≤ d} (expand p r) · ν_r` whenever
`deg p ≤ d`.  Existence comes from the triangular basis `X_pow_mem_span_nu`, uniqueness from
`expand_eq_of_span`. -/
theorem expand_spec [QGeneric K] {d : ℕ} {p : Polynomial K} (hdeg : p.natDegree < d + 1) :
    (∑ r ∈ Finset.range (d + 1), expand (G := G) p r • nu (G := G) r) = p := by
  have step1 : p ∈ Submodule.span K ((fun r => nu (G := G) r) '' ↑(Finset.range (d + 1))) := by
    nth_rewrite 1 [Polynomial.as_sum_range_C_mul_X_pow' p hdeg]
    refine Submodule.sum_mem _ fun i hi => ?_
    rw [← Polynomial.smul_eq_C_mul]
    exact Submodule.smul_mem _ _
      (X_pow_mem_span_nu_le (G := G) (Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)))
  obtain ⟨c, hc⟩ := (Submodule.mem_span_image_finset_iff_exists_fun' (R := K)).mp step1
  calc (∑ r ∈ Finset.range (d + 1), expand (G := G) p r • nu (G := G) r)
      = ∑ r ∈ Finset.range (d + 1), c r • nu (G := G) r :=
        Finset.sum_congr rfl fun r hr => by
          rw [expand_eq_of_span hc r (Nat.lt_succ_iff.mp (Finset.mem_range.mp hr))]
    _ = p := hc

/-- **The coordinates returned by `expand` are the ones that witness clause (iii).**
If `t ∈ 𝒩^ev` is cleared to a polynomial, `t·Y̌^N = p(Y̌)` with `deg p ≤ d`, then

* every Newton coordinate `expand p r` (`r ≤ d`) lies in `A_z` — this is the unitriangular
  pinning `CenterLattice.coeff_mem_of_grid_mem`, fed by `ev_χ(p) = Q^{Nχ}·ev_χ(t)`; and
* those coordinates reassemble `t`: `t = Σ_{r ≤ d} (expand p r) · Y̌^{-N} ν_r(Y̌)`.

`mem_span_of_Newton` is the one-line corollary. -/
theorem expand_witnesses_span [QGeneric K] {t : Frame K} (ht : Newton (G := G) t)
    {N : ℕ} {p : Polynomial K} (hp : Polynomial.toLaurent p = t * T (N : ℤ))
    {d : ℕ} (hdeg : p.natDegree < d + 1) :
    (∀ r ≤ d, expand (G := G) p r ∈ AzSubring (K := K)) ∧
      t = ∑ r ∈ Finset.range (d + 1), expand (G := G) p r • nuGen (G := G) (-(N : ℤ)) r := by
  classical
  have htN : (T (-(N : ℤ)) : Frame K) * Polynomial.toLaurent p = t := by
    rw [hp, LaurentPolynomial.T_mul, LaurentPolynomial.mul_T_assoc]
    simp
  have hc : (∑ r ∈ Finset.range (d + 1), expand (G := G) p r • nu (G := G) r) = p :=
    expand_spec hdeg
  have hval : ∀ L : ℕ, Polynomial.eval ((G.q ^ 2 : K) ^ L) p
      = newtonSum (K := K) d (expand (G := G) p) ((G.q ^ 2) ^ L) := by
    intro L
    conv_lhs => rw [← hc]
    rw [Polynomial.eval_finsetSum]
    unfold newtonSum
    refine Finset.sum_congr rfl fun r _ => ?_
    rw [Polynomial.smul_eq_C_mul, Polynomial.eval_mul, Polynomial.eval_C, eval_nu]
  have hgrid : ∀ L ≤ d,
      newtonSum (K := K) d (expand (G := G) p) ((G.q ^ 2) ^ L) ∈ AzSubring (K := K) := by
    intro L _
    have hpe : Polynomial.eval ((G.q ^ 2 : K) ^ L) p
        = grid (G := G) (L : ℤ) (Polynomial.toLaurent p) := by
      rw [grid_toLaurent, zpow_natCast]
    rw [← hval L, hpe, hp, map_mul, grid_T]
    exact mul_mem (ht (L : ℤ)) (Az_Qzpow_zpow (G := G) (L : ℤ) (N : ℤ))
  refine ⟨coeff_mem_of_grid_mem hgrid, ?_⟩
  rw [← htN]
  conv_lhs => rw [← hc]
  rw [map_sum, Finset.mul_sum]
  refine Finset.sum_congr rfl fun r _ => ?_
  rw [Polynomial.smul_eq_C_mul, map_mul, Polynomial.toLaurent_C,
    LaurentPolynomial.smul_eq_C_mul, nuGen]
  ring

/-- **The `⟹` leg.**  `𝒩^ev ⊆ Σ_u Σ_r A_z Y̌^u ν_r(Y̌)` (`PROOFv0a` Lemma 3 + Laurent
clearing).  This is the Harman–Hopkins content.

Route, following `PROOFv0a` §3.3–§3.4 and mirroring the certified two-variable
`UQ.NewtonSpan.mem_span_of_nuNewtonIntegral`:

* **Laurent clearing** — `LaurentPolynomial.exists_T_pow` gives `N` and a polynomial `p` with
  `Y̌^{-N}·p = t`;
* **windowed Newton expansion** — the triangular basis `X_pow_mem_span_nu` writes `p` as a
  `K`-combination `Σ_{r ≤ d} c_r ν_r`;
* **unitriangular pinning** — on the window `χ = 0,…,d` the evaluation matrix `V[m,r] = ν_r(Q^m)`
  is lower unitriangular with `A_z` entries, so `CenterLattice.coeff_mem_of_grid_mem` forces every
  `c_r ∈ A_z` (the grid values are `A_z` because `ev_χ(p) = Q^{Nχ}·ev_χ(t)` and `Q^{Nχ}` is an
  `A_z`-unit);
* **reassembly** — `t = Σ_r c_r · (Y̌^{-N} ν_r(Y̌))`, an `A_z`-combination of generators.

Steps 2–4 are packaged in `expand_witnesses_span`, which names the coordinate family: it is
`GL1Newton.expand p`, the mandated Newton coordinate map. -/
theorem mem_span_of_Newton [QGeneric K] {t : Frame K} (ht : Newton (G := G) t) :
    t ∈ Submodule.span (AzSubring (K := K)) (nuGenSet (G := G)) := by
  classical
  -- Laurent clearing: `toLaurent p = t · Y̌^N`, i.e. `t = Y̌^{-N} · p`.
  obtain ⟨N, p, hp⟩ := LaurentPolynomial.exists_T_pow t
  obtain ⟨d, hdeg⟩ : ∃ d : ℕ, p.natDegree < d + 1 := ⟨p.natDegree, Nat.lt_succ_self _⟩
  -- Windowed Newton expansion + unitriangular pinning + reassembly.
  obtain ⟨hmem, hsum⟩ := expand_witnesses_span (G := G) ht hp hdeg
  rw [hsum]
  refine Submodule.sum_mem _ fun r hr => ?_
  have hgen : nuGen (G := G) (-(N : ℤ)) r
      ∈ Submodule.span (AzSubring (K := K)) (nuGenSet (G := G)) :=
    Submodule.subset_span ⟨-(N : ℤ), r, rfl⟩
  exact Submodule.smul_mem _
    (⟨expand (G := G) p r, hmem r (Nat.lt_succ_iff.mp (Finset.mem_range.mp hr))⟩ :
      AzSubring (K := K)) hgen

/-- **`goalv0a` clause (iii)** (iff form):
`f ∈ 𝒩^ev ↔ f ∈ Σ_{u ∈ ℤ} Σ_{r ≥ 0} A_z · Y̌^u ν_r(Y̌)`. -/
theorem Newton_iff_mem_span [QGeneric K] (t : Frame K) :
    Newton (G := G) t ↔ t ∈ Submodule.span (AzSubring (K := K)) (nuGenSet (G := G)) :=
  ⟨mem_span_of_Newton, Newton_of_mem_span⟩

/-- **`goalv0a` clause (iii)** (set-equality form, the literal shape of the goal text):
`𝒩^ev = Σ_{u ∈ ℤ} Σ_{r ≥ 0} A_z · Y̌^u ν_r(Y̌)`. -/
theorem Nev_eq_span [QGeneric K] :
    {t : Frame K | Newton (G := G) t}
      = (Submodule.span (AzSubring (K := K)) (nuGenSet (G := G)) : Set (Frame K)) :=
  Set.ext fun t => Newton_iff_mem_span t

end GL1Newton
end A1
end HybridQuantumLean
