import Sandbox.A1.GL1.NewtonUnivGrid
import Mathlib.LinearAlgebra.Finsupp.VectorSpace
import Mathlib.RingTheory.Ideal.Quotient.Operations

set_option linter.style.header false
set_option linter.unusedSectionVars false

/-!
# `A1.GL1Newton.Presentation` — `goalv0a` Definition 1 proved, not assumed

Binding statement of record: `sandboxv0a/informal/goalv0a.lock.json`
(tex `91a50173…5a7e`, `sandboxv0a/informal/goalv0a.tex`), Definition 1.
Binding informal proof: `sandboxv0a/informal/PROOFv0a.tex`.

## What this file closes (verification finding F1)

`goalv0a` Definition 1 *presents* the hybrid family quantum `GL₁`:

> `U` is the `K_z`-algebra with invertible pairwise commuting generators `K_{n,±}` (`n ∈ ℤ`)
> subject to `K_{0,±} = 1`, `K_{m+n,±} = K_{m,±}K_{n,±}`, `K_{n,+}K_{n,-} = z^n`.
> Writing `T^± := K_{1,±}`, the monomials `(T⁺)^w` (`w ∈ ℤ`) form a `K_z`-basis of `U`.

The rest of `sandboxv0a` models `U` directly as the Laurent torus
(`NewtonUnivGrid.Torus K = LaurentPolynomial K`).  Until this file, that collapse — and with it
the relation `K_{n,+}K_{n,-} = z^n`, the **only** place where `z` enters the algebra structure of
`U` — was an unproved modelling assumption carried across the formalisation boundary.

Here the presented algebra is **constructed** and the collapse is **proved**:

* `Presentation.Free K = AddMonoidAlgebra K (ℤ × ℤ)` is the free object on invertible pairwise
  commuting `K_{m,+}, K_{n,-}` with `K_{0,±} = 1` and `K_{m+n,±} = K_{m,±}K_{n,±}` — i.e. the
  group algebra of the free abelian group `ℤ⟨T⁺⟩ ⊕ ℤ⟨T⁻⟩`, which is exactly what those two
  relations say (`gen`, `gen_mul`, `gen_zero`, `gen_zpow`).
* `Presentation.relIdeal z` is the ideal generated by the single remaining relation
  `T⁺T⁻ − z`, and `Presentation.U z := Free K ⧸ relIdeal z` is the presented algebra.
  The **full** family `K_{n,+}K_{n,-} = z^n` (`n : ℤ`, both signs) is then a *theorem*, not an
  imposed relation: `uData.Kplus_mul_Kminus`.
* `Presentation.equivTorus z hz : U z ≃ₐ[K] Torus K` is the collapse, proved by exhibiting the
  two `K`-algebra maps and both composites (`toTorus_fromTorus`, `fromTorus_comp_toTorus`).
* `torusData_Kminus`/`torusData_Kminus_eq_zpow` exhibit the elimination of the negative
  generators: **`K_{n,-} = z^n (T⁺)^{-n}`**.
* `torusBasis`/`uBasis` prove Definition 1's final sentence — the monomials `(T⁺)^w`, `w ∈ ℤ`,
  really are a basis of `U` (`uBasis_apply : uBasis z hz w = K_{w,+}`).
* `existsUnique_lift` checks the remaining encoding step in the kernel: `U z` is **initial**
  among presentation data, so it is the presented algebra in the only sense the phrase has, and
  the identification of `Free K` with the free object on the generators is not merely asserted.

## Two recorded deviations (neither weakens anything)

1. **Coefficient field.**  `goalv0a` presents `U` over `K_z = ℚ(q)[z^{±1}]`; this file works over
   an arbitrary field `K` containing the parameter `z ≠ 0`, and the model instantiates it at
   `K₁ = Frac(ℤ[q^±, z^±]) ⊋ K_z`.  This is the already-recorded strengthening (verification
   finding F4): the basis and the presentation are stated over the larger field.
2. **`z` as a parameter.**  `z` is a *nonzero element of the coefficient field*, not an
   indeterminate adjoined here; over the model field `K₁` it is the Laurent variable `zK`
   (`FamilyField1`), and `modelEquiv` pins the instantiation at `G.z`.

## Why the *commutative* free object is the right one

`goalv0a` Def 1 says the generators are **pairwise commuting**, and `U` is generated by them, so
`U` is commutative.  The free object on invertible pairwise commuting `K_{m,+}, K_{n,-}` in
commutative `K`-algebras is therefore the correct ambient, and that is the group algebra
`K[ℤ × ℤ] = Free K`.  Accordingly `Data` is stated for commutative `A` — no generality is lost
and none is silently gained.

## Status

Complete and `sorry`-free.
-/

namespace HybridQuantumLean
namespace A1
namespace GL1Newton
namespace Presentation

open LaurentPolynomial
open HybridQuantumLean.A1.Verma
open HybridQuantumLean.A1.Verma.GL2

universe u v

variable {K : Type u} [Field K]

/-! ## 1. The presentation data -/

/-- **`goalv0a` Definition 1, as data.**  A `Data z A` is a choice of generators `K_{n,±}` in a
commutative `K`-algebra `A` satisfying exactly the relations of `goalv0a` Def 1: invertibility,
`K_{0,±} = 1`, `K_{m+n,±} = K_{m,±}K_{n,±}`, and `K_{n,+}K_{n,-} = z^n`.  (Pairwise commutativity
is automatic: `A` is commutative, matching `Φ = ∅`.) -/
structure Data (z : K) (A : Type v) [CommRing A] [Algebra K A] where
  Kplus : ℤ → A
  Kminus : ℤ → A
  isUnit_Kplus : ∀ n, IsUnit (Kplus n)
  isUnit_Kminus : ∀ n, IsUnit (Kminus n)
  Kplus_zero : Kplus 0 = 1
  Kminus_zero : Kminus 0 = 1
  Kplus_add : ∀ m n, Kplus (m + n) = Kplus m * Kplus n
  Kminus_add : ∀ m n, Kminus (m + n) = Kminus m * Kminus n
  Kplus_mul_Kminus : ∀ n, Kplus n * Kminus n = algebraMap K A (z ^ n)

/-! ## 2. The free algebra -/

/-- **The free object on the generators.**  The relations `K_{0,±} = 1` and
`K_{m+n,±} = K_{m,±}K_{n,±}` say precisely that `m ↦ K_{m,+}` and `n ↦ K_{n,-}` are group
homomorphisms `ℤ → Aˣ`, so the universal algebra carrying them is the group algebra of
`ℤ × ℤ` — with `(m, n)` standing for `K_{m,+}K_{n,-}`. -/
abbrev Free (K : Type u) [Field K] : Type u := AddMonoidAlgebra K (ℤ × ℤ)

/-- The monomial `K_{g.1,+}K_{g.2,-}` as a **unit** of the free algebra. -/
noncomputable def gen (g : ℤ × ℤ) : (Free K)ˣ where
  val := AddMonoidAlgebra.single g 1
  inv := AddMonoidAlgebra.single (-g) 1
  val_inv := by rw [AddMonoidAlgebra.single_mul_single, one_mul, add_neg_cancel]; rfl
  inv_val := by rw [AddMonoidAlgebra.single_mul_single, one_mul, neg_add_cancel]; rfl

@[simp] theorem gen_val (g : ℤ × ℤ) :
    ((gen (K := K) g : (Free K)ˣ) : Free K) = AddMonoidAlgebra.single g 1 := rfl

theorem gen_mul (g h : ℤ × ℤ) : gen (K := K) g * gen h = gen (g + h) := by
  refine Units.ext ?_
  simp [AddMonoidAlgebra.single_mul_single]

theorem gen_zero : gen (K := K) 0 = 1 := Units.ext (by simp; rfl)

theorem gen_inv (g : ℤ × ℤ) : (gen (K := K) g)⁻¹ = gen (-g) := Units.ext rfl

theorem gen_zpow (g : ℤ × ℤ) (n : ℤ) : gen (K := K) g ^ n = gen (n • g) := by
  induction n using Int.induction_on with
  | zero => simpa using gen_zero
  | succ k ih =>
    rw [zpow_add_one, ih, gen_mul]
    congr 1
    module
  | pred k ih =>
    rw [zpow_sub_one, ih, gen_inv, gen_mul]
    congr 1
    module

@[simp] theorem val_gen_zpow (g : ℤ × ℤ) (n : ℤ) :
    ((gen (K := K) g ^ n : (Free K)ˣ) : Free K) = AddMonoidAlgebra.single (n • g) 1 := by
  rw [gen_zpow]; rfl


/-! ## 3. The relation ideal and the presented algebra -/

/-- **The relation ideal.**  Only `K_{1,+}K_{1,-} = z` has to be imposed: everything commutes, so
`K_{n,+}K_{n,-} = (K_{1,+}K_{1,-})^n = z^n` follows for every `n : ℤ` (proved as
`uData.Kplus_mul_Kminus`). -/
noncomputable def relIdeal (z : K) : Ideal (Free K) :=
  Ideal.span {(gen (K := K) (1, 0) : Free K) * (gen (K := K) (0, 1) : Free K)
    - algebraMap K (Free K) z}

/-- **`U`** — the algebra presented by `goalv0a` Definition 1: the free algebra on the generators
modulo exactly the stated relations. -/
abbrev U (z : K) : Type u := Free K ⧸ relIdeal (K := K) z

-- Sanity: the presented algebra really is a commutative `K`-algebra.
noncomputable example (z : K) : CommRing (U (K := K) z) := inferInstance
noncomputable example (z : K) : Algebra K (U (K := K) z) := inferInstance

/-! ## 4. The Laurent torus carries the presentation -/

/-- The intended image of the monomial `K_{a,+}K_{b,-}` in the Laurent torus:
`T^a · (z T^{-1})^b = z^b T^{a-b}`. -/
noncomputable def torusFun (z : K) (g : ℤ × ℤ) : Torus K :=
  LaurentPolynomial.C (z ^ g.2) * T (g.1 - g.2)

theorem torusFun_add (z : K) (hz : z ≠ 0) (g h : ℤ × ℤ) :
    torusFun z (g + h) = torusFun z g * torusFun z h := by
  obtain ⟨a, b⟩ := g
  obtain ⟨c, d⟩ := h
  simp only [torusFun, Prod.fst_add, Prod.snd_add]
  rw [zpow_add₀ hz, map_mul, show a + c - (b + d) = (a - b) + (c - d) from by ring,
    LaurentPolynomial.T_add]
  ring

/-- `torusFun` is multiplicative, hence a monoid hom out of the group `Multiplicative (ℤ × ℤ)`. -/
noncomputable def torusHom (z : K) (hz : z ≠ 0) : Multiplicative (ℤ × ℤ) →* Torus K where
  toFun g := torusFun z (Multiplicative.toAdd g)
  map_one' := by simp [torusFun]
  map_mul' x y := torusFun_add z hz _ _

/-- The `K`-algebra map out of the free algebra determined by `torusHom` (universal property of
the monoid algebra, `AddMonoidAlgebra.lift`). -/
noncomputable def freeToTorus (z : K) (hz : z ≠ 0) : Free K →ₐ[K] Torus K :=
  AddMonoidAlgebra.lift K (Torus K) (ℤ × ℤ) (torusHom z hz)

@[simp] theorem freeToTorus_single (z : K) (hz : z ≠ 0) (g : ℤ × ℤ) :
    freeToTorus z hz (AddMonoidAlgebra.single g 1)
      = LaurentPolynomial.C (z ^ g.2) * T (g.1 - g.2) := by
  rw [freeToTorus, AddMonoidAlgebra.lift_single]
  simp [torusHom, torusFun]


/-! ## 5. The comparison maps -/

theorem freeToTorus_rel (z : K) (hz : z ≠ 0) :
    freeToTorus z hz ((gen (K := K) (1, 0) : Free K) * (gen (K := K) (0, 1) : Free K)
      - algebraMap K (Free K) z) = 0 := by
  rw [map_sub, map_mul, AlgHom.commutes, gen_val, gen_val, freeToTorus_single,
    freeToTorus_single]
  simp [← LaurentPolynomial.C_eq_algebraMap]

/-- `freeToTorus` kills the relation, so it descends to the presented algebra. -/
noncomputable def toTorus (z : K) (hz : z ≠ 0) : U (K := K) z →ₐ[K] Torus K :=
  Ideal.Quotient.liftₐ _ (freeToTorus z hz) (by
    have hle : relIdeal (K := K) z
        ≤ RingHom.ker (freeToTorus z hz : Free K →+* Torus K) := by
      refine Ideal.span_le.mpr ?_
      rintro x hx
      rw [Set.mem_singleton_iff] at hx
      subst hx
      exact freeToTorus_rel z hz
    exact fun a ha => hle ha)

@[simp] theorem toTorus_mk (z : K) (hz : z ≠ 0) (x : Free K) :
    toTorus z hz (Ideal.Quotient.mk (relIdeal (K := K) z) x) = freeToTorus z hz x := rfl

/-- The image of `gen g` in the presented algebra, as a unit. -/
noncomputable def uGen (z : K) (g : ℤ × ℤ) : (U (K := K) z)ˣ :=
  Units.map (Ideal.Quotient.mk (relIdeal (K := K) z)).toMonoidHom (gen g)

/-- **`T⁺ = K_{1,+}`** in the presented algebra. -/
noncomputable def uTp (z : K) : (U (K := K) z)ˣ := uGen z (1, 0)
/-- **`T⁻ = K_{1,-}`** in the presented algebra. -/
noncomputable def uTm (z : K) : (U (K := K) z)ˣ := uGen z (0, 1)

/-- The inverse comparison map `Torus K → U`, `T ↦ T⁺` (`LaurentPolynomial.eval₂` at the unit
`uTp`, upgraded to a `K`-algebra map). -/
noncomputable def fromTorus (z : K) : Torus K →ₐ[K] U (K := K) z :=
  { LaurentPolynomial.eval₂ (algebraMap K (U (K := K) z)) (uTp z) with
    commutes' := fun c => by
      change LaurentPolynomial.eval₂ (algebraMap K (U (K := K) z)) (uTp z)
          (algebraMap K (Torus K) c) = _
      rw [← LaurentPolynomial.C_eq_algebraMap, LaurentPolynomial.eval₂_C] }

@[simp] theorem fromTorus_T (z : K) (n : ℤ) :
    fromTorus z (T n : Torus K) = ((uTp z ^ n : (U (K := K) z)ˣ) : U (K := K) z) := by
  change LaurentPolynomial.eval₂ (algebraMap K (U (K := K) z)) (uTp z) (T n) = _
  rw [LaurentPolynomial.eval₂_T]

@[simp] theorem fromTorus_C (z : K) (c : K) :
    fromTorus z (LaurentPolynomial.C c : Torus K) = algebraMap K (U (K := K) z) c := by
  change LaurentPolynomial.eval₂ (algebraMap K (U (K := K) z)) (uTp z) (LaurentPolynomial.C c) = _
  rw [LaurentPolynomial.eval₂_C]


/-! ## 6. The two composites -/

theorem toTorus_uTp (z : K) (hz : z ≠ 0) :
    toTorus z hz ((uTp z : U (K := K) z)) = (T 1 : Torus K) := by
  change toTorus z hz (Ideal.Quotient.mk (relIdeal (K := K) z)
      (AddMonoidAlgebra.single ((1, 0) : ℤ × ℤ) 1)) = _
  rw [toTorus_mk, freeToTorus_single]
  simp

theorem toTorus_uTp_zpow (z : K) (hz : z ≠ 0) (n : ℤ) :
    toTorus z hz ((uTp z ^ n : (U (K := K) z)ˣ) : U (K := K) z) = (T n : Torus K) := by
  have h1 : Units.map (toTorus z hz : U (K := K) z →* Torus K) (uTp z)
      = (isUnit_T (1 : ℤ)).unit := by
    refine Units.ext ?_
    rw [Units.coe_map, IsUnit.unit_spec]
    exact toTorus_uTp z hz
  calc toTorus z hz ((uTp z ^ n : (U (K := K) z)ˣ) : U (K := K) z)
      = ((Units.map (toTorus z hz : U (K := K) z →* Torus K) (uTp z ^ n) :
            (Torus K)ˣ) : Torus K) := rfl
    _ = (((Units.map (toTorus z hz : U (K := K) z →* Torus K) (uTp z)) ^ n :
            (Torus K)ˣ) : Torus K) := by rw [map_zpow]
    _ = (T (n * 1) : Torus K) := by rw [h1]; exact val_unit_T_zpow 1 n
    _ = (T n : Torus K) := by rw [mul_one]

theorem toTorus_fromTorus (z : K) (hz : z ≠ 0) (f : Torus K) :
    toTorus z hz (fromTorus z f) = f := by
  induction f using LaurentPolynomial.induction_on' with
  | add p q hp hq => rw [map_add, map_add, hp, hq]
  | C_mul_T n a =>
    rw [map_mul, map_mul, fromTorus_C, fromTorus_T, AlgHom.commutes, toTorus_uTp_zpow,
      ← LaurentPolynomial.C_eq_algebraMap]

/-! ### The other composite -/

theorem gen_fst (a : ℤ) : gen (K := K) (a, 0) = gen (K := K) (1, 0) ^ a := by
  rw [gen_zpow]; congr 1; simp

theorem gen_snd (b : ℤ) : gen (K := K) (0, b) = gen (K := K) (0, 1) ^ b := by
  rw [gen_zpow]; congr 1; simp

theorem gen_split (g : ℤ × ℤ) :
    gen (K := K) g = gen (K := K) (g.1, 0) * gen (K := K) (0, g.2) := by
  rw [gen_mul]; congr 1; simp

theorem uGen_split (z : K) (g : ℤ × ℤ) :
    uGen z g = uTp z ^ g.1 * uTm z ^ g.2 := by
  rw [uGen, gen_split, map_mul, gen_fst, gen_snd, map_zpow, map_zpow]
  rfl

/-- The scalar `z` as a unit of the presented algebra. -/
noncomputable def uZ (z : K) (hz : z ≠ 0) : (U (K := K) z)ˣ :=
  Units.map (algebraMap K (U (K := K) z) : K →* U (K := K) z) (Units.mk0 z hz)

theorem val_uZ_zpow (z : K) (hz : z ≠ 0) (b : ℤ) :
    ((uZ z hz ^ b : (U (K := K) z)ˣ) : U (K := K) z)
      = algebraMap K (U (K := K) z) (z ^ b) := by
  rw [uZ, ← map_zpow, Units.coe_map]
  simp

theorem uTp_mul_uTm (z : K) (hz : z ≠ 0) : uTp z * uTm z = uZ z hz := by
  refine Units.ext ?_
  change Ideal.Quotient.mk (relIdeal (K := K) z)
      ((gen (K := K) (1, 0) : Free K) * (gen (K := K) (0, 1) : Free K))
    = algebraMap K (U (K := K) z) z
  rw [show algebraMap K (U (K := K) z) z
      = Ideal.Quotient.mk (relIdeal (K := K) z) (algebraMap K (Free K) z) from rfl,
    Ideal.Quotient.eq]
  exact Ideal.subset_span rfl

theorem uTm_eq (z : K) (hz : z ≠ 0) : uTm z = uZ z hz * (uTp z)⁻¹ :=
  eq_mul_inv_iff_mul_eq.mpr ((mul_comm (uTm z) (uTp z)).trans (uTp_mul_uTm z hz))

theorem uGen_eq_units (z : K) (hz : z ≠ 0) (g : ℤ × ℤ) :
    uGen z g = uZ z hz ^ g.2 * uTp z ^ (g.1 - g.2) := by
  rw [uGen_split, uTm_eq z hz, mul_zpow (uZ z hz) ((uTp z)⁻¹) g.2, inv_zpow,
    zpow_sub (uTp z) g.1 g.2]
  exact mul_left_comm (uTp z ^ g.1) (uZ z hz ^ g.2) ((uTp z ^ g.2)⁻¹)

theorem val_uGen_eq (z : K) (hz : z ≠ 0) (g : ℤ × ℤ) :
    ((uGen z g : (U (K := K) z)ˣ) : U (K := K) z)
      = algebraMap K (U (K := K) z) (z ^ g.2)
        * ((uTp z ^ (g.1 - g.2) : (U (K := K) z)ˣ) : U (K := K) z) := by
  rw [uGen_eq_units z hz, Units.val_mul, val_uZ_zpow]

theorem fromTorus_comp_toTorus (z : K) (hz : z ≠ 0) :
    (fromTorus z).comp (toTorus z hz) = AlgHom.id K (U (K := K) z) := by
  refine Ideal.Quotient.algHom_ext K ?_
  refine AddMonoidAlgebra.algHom_ext ?_
  intro g
  change fromTorus z (toTorus z hz (Ideal.Quotient.mk (relIdeal (K := K) z)
      (AddMonoidAlgebra.single g 1)))
    = Ideal.Quotient.mk (relIdeal (K := K) z) (AddMonoidAlgebra.single g 1)
  rw [toTorus_mk, freeToTorus_single, map_mul, fromTorus_C, fromTorus_T, ← val_uGen_eq z hz g]
  rfl

/-! ## 7. The isomorphism -/

/-- **The presentation-to-Laurent collapse, proved.**  The algebra presented by `goalv0a`
Definition 1 is `K`-algebra isomorphic to the Laurent torus `Torus K = K[(T⁺)^{±1}]`.
This is the statement the wave-2 delivery assumed (verification finding F1). -/
noncomputable def equivTorus (z : K) (hz : z ≠ 0) : U (K := K) z ≃ₐ[K] Torus K :=
  AlgEquiv.ofAlgHom (toTorus z hz) (fromTorus z)
    (AlgHom.ext fun f => toTorus_fromTorus z hz f)
    (fromTorus_comp_toTorus z hz)


/-! ## 8. The Laurent torus as a presented algebra -/

/-- **The Laurent torus carries the presentation**, with `K_{n,+} = T^n` and
`K_{n,-} = z^n T^{-n}` — the elimination of the negative generators forced by
`K_{n,+}K_{n,-} = z^n`. -/
noncomputable def torusData (z : K) (hz : z ≠ 0) : Data z (Torus K) where
  Kplus n := T n
  Kminus n := LaurentPolynomial.C (z ^ n) * T (-n)
  isUnit_Kplus n := isUnit_T n
  isUnit_Kminus n := by
    refine ⟨⟨LaurentPolynomial.C (z ^ n) * T (-n),
      LaurentPolynomial.C (z ^ (-n)) * T n, ?_, ?_⟩, rfl⟩
    · rw [mul_mul_mul_comm, ← map_mul, ← LaurentPolynomial.T_add, ← zpow_add₀ hz]
      simp
    · rw [mul_mul_mul_comm, ← map_mul, ← LaurentPolynomial.T_add, ← zpow_add₀ hz]
      simp
  Kplus_zero := by simp
  Kminus_zero := by simp
  Kplus_add m n := LaurentPolynomial.T_add m n
  Kminus_add m n := by
    rw [zpow_add₀ hz, map_mul, mul_mul_mul_comm, ← LaurentPolynomial.T_add]
    congr 2
    ring
  Kplus_mul_Kminus n := by
    rw [← mul_assoc, mul_comm (T n : Torus K), mul_assoc, ← LaurentPolynomial.T_add]
    simp [← LaurentPolynomial.C_eq_algebraMap]

@[simp] theorem torusData_Kplus (z : K) (hz : z ≠ 0) (n : ℤ) :
    (torusData z hz).Kplus n = (T n : Torus K) := rfl

@[simp] theorem torusData_Kminus (z : K) (hz : z ≠ 0) (n : ℤ) :
    (torusData z hz).Kminus n = LaurentPolynomial.C (z ^ n) * (T (-n) : Torus K) := rfl

theorem torusData_Kplus_eq_zpow (z : K) (hz : z ≠ 0) (n : ℤ) :
    (torusData z hz).Kplus n
      = ((((isUnit_T (1 : ℤ)).unit) ^ n : (Torus K)ˣ) : Torus K) := by
  rw [torusData_Kplus, val_unit_T_zpow 1 n, mul_one]

theorem torusData_Kminus_eq_zpow (z : K) (hz : z ≠ 0) (n : ℤ) :
    (torusData z hz).Kminus n
      = LaurentPolynomial.C (z ^ n)
        * ((((isUnit_T (1 : ℤ)).unit) ^ (-n) : (Torus K)ˣ) : Torus K) := by
  rw [torusData_Kminus, val_unit_T_zpow 1 (-n), mul_one]

/-! ## 9. The presentation data carried by `U`, and its image under the isomorphism -/

/-- **The presented algebra carries its own presentation**, by the images of the generators.
The field `Kplus_mul_Kminus` is where the full family `K_{n,+}K_{n,-} = z^n` (`n : ℤ`, both
signs) is *derived* from the single imposed relation. -/
noncomputable def uData (z : K) (hz : z ≠ 0) : Data z (U (K := K) z) where
  Kplus n := ((uTp z ^ n : (U (K := K) z)ˣ) : U (K := K) z)
  Kminus n := ((uTm z ^ n : (U (K := K) z)ˣ) : U (K := K) z)
  isUnit_Kplus n := Units.isUnit _
  isUnit_Kminus n := Units.isUnit _
  Kplus_zero := by simp
  Kminus_zero := by simp
  Kplus_add m n := by rw [zpow_add, Units.val_mul]
  Kminus_add m n := by rw [zpow_add, Units.val_mul]
  Kplus_mul_Kminus n := by
    rw [← Units.val_mul, ← mul_zpow (uTp z) (uTm z) n, uTp_mul_uTm z hz, val_uZ_zpow]

@[simp] theorem uData_Kplus (z : K) (hz : z ≠ 0) (n : ℤ) :
    (uData z hz).Kplus n = ((uTp z ^ n : (U (K := K) z)ˣ) : U (K := K) z) := rfl

@[simp] theorem uData_Kminus (z : K) (hz : z ≠ 0) (n : ℤ) :
    (uData z hz).Kminus n = ((uTm z ^ n : (U (K := K) z)ˣ) : U (K := K) z) := rfl

@[simp] theorem equivTorus_apply (z : K) (hz : z ≠ 0) (x : U (K := K) z) :
    equivTorus z hz x = toTorus z hz x := rfl

@[simp] theorem equivTorus_symm_apply (z : K) (hz : z ≠ 0) (f : Torus K) :
    (equivTorus z hz).symm f = fromTorus z f := rfl

theorem equivTorus_Kplus (z : K) (hz : z ≠ 0) (n : ℤ) :
    equivTorus z hz ((uData z hz).Kplus n) = (torusData z hz).Kplus n :=
  toTorus_uTp_zpow z hz n

theorem equivTorus_Kminus (z : K) (hz : z ≠ 0) (n : ℤ) :
    equivTorus z hz ((uData z hz).Kminus n) = (torusData z hz).Kminus n := by
  rw [equivTorus_apply, uData_Kminus, uTm_eq z hz, mul_zpow (uZ z hz) ((uTp z)⁻¹) n,
    inv_zpow, ← zpow_neg,
    Units.val_mul, map_mul, val_uZ_zpow, AlgHom.commutes, toTorus_uTp_zpow,
    torusData_Kminus, ← LaurentPolynomial.C_eq_algebraMap]

/-! ## 10. The `(T⁺)^w` basis -/

/-- **`goalv0a` Def 1, final sentence, on the Laurent model**: the monomials `T^w`, `w ∈ ℤ`,
form a `K`-basis of the torus. -/
noncomputable def torusBasis (K : Type u) [Field K] : Module.Basis ℤ K (Torus K) :=
  Finsupp.basisSingleOne

@[simp] theorem torusBasis_apply (w : ℤ) : torusBasis K w = (T w : Torus K) := by
  have h : torusBasis K w = (Finsupp.single w (1 : K) : Torus K) :=
    congrFun Finsupp.coe_basisSingleOne w
  rw [h]
  rfl

/-- **`goalv0a` Def 1, final sentence, proved on the presented algebra**: the monomials
`(T⁺)^w = K_{w,+}`, `w ∈ ℤ`, form a `K`-basis of `U` (`uBasis_apply`). -/
noncomputable def uBasis (z : K) (hz : z ≠ 0) : Module.Basis ℤ K (U (K := K) z) :=
  (torusBasis K).map (equivTorus z hz).symm.toLinearEquiv

@[simp] theorem uBasis_apply (z : K) (hz : z ≠ 0) (w : ℤ) :
    uBasis z hz w = (uData z hz).Kplus w := by
  rw [uBasis, Module.Basis.map_apply, torusBasis_apply]
  exact fromTorus_T z w


/-! ## 10a. The universal property: `U` really is the algebra **presented** by Definition 1

The construction above encodes the relations `K_{0,±} = 1` and `K_{m+n,±} = K_{m,±}K_{n,±}` in the
*choice* of `Free K = K[ℤ × ℤ]`.  This section checks that choice in the kernel: `U z`, carrying
`uData z hz`, is **initial** among all presentation data.  Consequently `U z` is the presented
algebra in the only sense the phrase has, and — via `equivTorus` — so is `Torus K`. -/

section Universal

variable {z : K} {A : Type v} [CommRing A] [Algebra K A]

/-- `T⁺ = K_{1,+}` of a presentation datum, as a unit. -/
noncomputable def Data.up (d : Data z A) : Aˣ := (d.isUnit_Kplus 1).unit
/-- `T⁻ = K_{1,-}` of a presentation datum, as a unit. -/
noncomputable def Data.um (d : Data z A) : Aˣ := (d.isUnit_Kminus 1).unit

@[simp] theorem Data.val_up (d : Data z A) : ((d.up : Aˣ) : A) = d.Kplus 1 :=
  IsUnit.unit_spec _
@[simp] theorem Data.val_um (d : Data z A) : ((d.um : Aˣ) : A) = d.Kminus 1 :=
  IsUnit.unit_spec _

/-- `K_{n,+} = (T⁺)^n` for every `n : ℤ`, both signs — forced by `K_{0,+} = 1`,
`K_{m+n,+} = K_{m,+}K_{n,+}` and invertibility. -/
theorem Data.Kplus_zpow (d : Data z A) (n : ℤ) : d.Kplus n = ((d.up ^ n : Aˣ) : A) := by
  induction n using Int.induction_on with
  | zero => simpa using d.Kplus_zero
  | succ k ih => rw [d.Kplus_add, ih, zpow_add_one, Units.val_mul, Data.val_up]
  | pred k ih =>
    have hstep : d.Kplus (-(k : ℤ)) = d.Kplus (-(k : ℤ) - 1) * d.Kplus 1 := by
      have h := d.Kplus_add (-(k : ℤ) - 1) 1
      rwa [show -(k : ℤ) - 1 + 1 = -(k : ℤ) from by ring] at h
    have hcalc : d.Kplus (-(k : ℤ) - 1)
        = d.Kplus (-(k : ℤ)) * ((d.up⁻¹ : Aˣ) : A) := by
      rw [hstep, ← Data.val_up, mul_assoc, ← Units.val_mul, mul_inv_cancel, Units.val_one,
        mul_one]
    rw [hcalc, ih, zpow_sub_one, Units.val_mul]

/-- `K_{n,-} = (T⁻)^n` for every `n : ℤ`, both signs. -/
theorem Data.Kminus_zpow (d : Data z A) (n : ℤ) : d.Kminus n = ((d.um ^ n : Aˣ) : A) := by
  induction n using Int.induction_on with
  | zero => simpa using d.Kminus_zero
  | succ k ih => rw [d.Kminus_add, ih, zpow_add_one, Units.val_mul, Data.val_um]
  | pred k ih =>
    have hstep : d.Kminus (-(k : ℤ)) = d.Kminus (-(k : ℤ) - 1) * d.Kminus 1 := by
      have h := d.Kminus_add (-(k : ℤ) - 1) 1
      rwa [show -(k : ℤ) - 1 + 1 = -(k : ℤ) from by ring] at h
    have hcalc : d.Kminus (-(k : ℤ) - 1)
        = d.Kminus (-(k : ℤ)) * ((d.um⁻¹ : Aˣ) : A) := by
      rw [hstep, ← Data.val_um, mul_assoc, ← Units.val_mul, mul_inv_cancel, Units.val_one,
        mul_one]
    rw [hcalc, ih, zpow_sub_one, Units.val_mul]


/-- The image of the free monomial `(a, b) ↦ K_{a,+}K_{b,-}` in a presentation datum. -/
noncomputable def Data.mon (d : Data z A) (g : ℤ × ℤ) : Aˣ := d.up ^ g.1 * d.um ^ g.2

theorem Data.mon_add (d : Data z A) (g h : ℤ × ℤ) :
    d.mon (g + h) = d.mon g * d.mon h := by
  obtain ⟨a, b⟩ := g
  obtain ⟨c, e⟩ := h
  simp only [Data.mon, Prod.fst_add, Prod.snd_add]
  rw [zpow_add, zpow_add]
  exact mul_mul_mul_comm (d.up ^ a) (d.up ^ c) (d.um ^ b) (d.um ^ e)

/-- `Data.mon` as a monoid hom out of `Multiplicative (ℤ × ℤ)`. -/
noncomputable def Data.hom (d : Data z A) : Multiplicative (ℤ × ℤ) →* A where
  toFun g := ((d.mon (Multiplicative.toAdd g) : Aˣ) : A)
  map_one' := by simp [Data.mon]
  map_mul' x y := by
    rw [← Units.val_mul]
    exact congrArg Units.val (d.mon_add (Multiplicative.toAdd x) (Multiplicative.toAdd y))

/-- The `K`-algebra map out of the free algebra determined by a presentation datum. -/
noncomputable def Data.freeLift (d : Data z A) : Free K →ₐ[K] A :=
  AddMonoidAlgebra.lift K A (ℤ × ℤ) d.hom

@[simp] theorem Data.freeLift_single (d : Data z A) (g : ℤ × ℤ) :
    d.freeLift (AddMonoidAlgebra.single g 1) = ((d.mon g : Aˣ) : A) := by
  rw [Data.freeLift, AddMonoidAlgebra.lift_single]
  simp [Data.hom]

/-- **Existence half of the universal property.**  A presentation datum in `A` satisfies the
relation `T⁺T⁻ = z`, so `Data.freeLift` descends to the presented algebra. -/
noncomputable def Data.lift (d : Data z A) : U (K := K) z →ₐ[K] A :=
  Ideal.Quotient.liftₐ _ d.freeLift (by
    have hle : relIdeal (K := K) z ≤ RingHom.ker (d.freeLift : Free K →+* A) := by
      refine Ideal.span_le.mpr ?_
      rintro x hx
      rw [Set.mem_singleton_iff] at hx
      subst hx
      have hone : d.mon (1, 0) = d.up := by simp [Data.mon]
      have htwo : d.mon (0, 1) = d.um := by simp [Data.mon]
      have hrel := d.Kplus_mul_Kminus 1
      rw [zpow_one] at hrel
      change d.freeLift _ = 0
      rw [map_sub, map_mul, AlgHom.commutes, gen_val, gen_val, Data.freeLift_single,
        Data.freeLift_single, hone, htwo, Data.val_up, Data.val_um, hrel, sub_self]
    exact fun a ha => hle ha)

@[simp] theorem Data.lift_mk (d : Data z A) (x : Free K) :
    d.lift (Ideal.Quotient.mk (relIdeal (K := K) z) x) = d.freeLift x := rfl

/-- `Data.lift` sends `T⁺` to `T⁺`. -/
theorem Data.map_uTp (d : Data z A) :
    Units.map (d.lift : U (K := K) z →* A) (uTp z) = d.up := by
  refine Units.ext ?_
  rw [Units.coe_map]
  change d.lift (Ideal.Quotient.mk (relIdeal (K := K) z)
    (AddMonoidAlgebra.single ((1, 0) : ℤ × ℤ) 1)) = _
  rw [Data.lift_mk, Data.freeLift_single]
  simp [Data.mon]

/-- `Data.lift` sends `T⁻` to `T⁻`. -/
theorem Data.map_uTm (d : Data z A) :
    Units.map (d.lift : U (K := K) z →* A) (uTm z) = d.um := by
  refine Units.ext ?_
  rw [Units.coe_map]
  change d.lift (Ideal.Quotient.mk (relIdeal (K := K) z)
    (AddMonoidAlgebra.single ((0, 1) : ℤ × ℤ) 1)) = _
  rw [Data.lift_mk, Data.freeLift_single]
  simp [Data.mon]

/-- `Data.lift` matches the positive generators. -/
theorem Data.lift_Kplus (d : Data z A) (hz : z ≠ 0) (n : ℤ) :
    d.lift ((uData z hz).Kplus n) = d.Kplus n := by
  rw [uData_Kplus, Data.Kplus_zpow, ← d.map_uTp, ← map_zpow, Units.coe_map]
  rfl

/-- `Data.lift` matches the negative generators. -/
theorem Data.lift_Kminus (d : Data z A) (hz : z ≠ 0) (n : ℤ) :
    d.lift ((uData z hz).Kminus n) = d.Kminus n := by
  rw [uData_Kminus, Data.Kminus_zpow, ← d.map_uTm, ← map_zpow, Units.coe_map]
  rfl

/-- **Uniqueness half of the universal property.**  A `K`-algebra map out of the presented
algebra is determined by its values on `T⁺` and `T⁻`. -/
theorem Data.lift_unique (d : Data z A) (hz : z ≠ 0) (f : U (K := K) z →ₐ[K] A)
    (h1 : f ((uData z hz).Kplus 1) = d.Kplus 1)
    (h2 : f ((uData z hz).Kminus 1) = d.Kminus 1) : f = d.lift := by
  have hp : Units.map (f : U (K := K) z →* A) (uTp z) = d.up := by
    refine Units.ext ?_
    rw [Units.coe_map, Data.val_up, ← h1, uData_Kplus, zpow_one]
    rfl
  have hm : Units.map (f : U (K := K) z →* A) (uTm z) = d.um := by
    refine Units.ext ?_
    rw [Units.coe_map, Data.val_um, ← h2, uData_Kminus, zpow_one]
    rfl
  refine Ideal.Quotient.algHom_ext K ?_
  refine AddMonoidAlgebra.algHom_ext ?_
  intro g
  have hgen : (Ideal.Quotient.mk (relIdeal (K := K) z) (AddMonoidAlgebra.single g 1))
      = ((uTp z ^ g.1 * uTm z ^ g.2 : (U (K := K) z)ˣ) : U (K := K) z) := by
    rw [← uGen_split z g]
    rfl
  change f (Ideal.Quotient.mk (relIdeal (K := K) z) (AddMonoidAlgebra.single g 1))
    = d.lift (Ideal.Quotient.mk (relIdeal (K := K) z) (AddMonoidAlgebra.single g 1))
  rw [hgen]
  have e1 : ∀ (F : U (K := K) z →ₐ[K] A),
      F ((uTp z ^ g.1 * uTm z ^ g.2 : (U (K := K) z)ˣ) : U (K := K) z)
        = ((Units.map (F : U (K := K) z →* A) (uTp z) ^ g.1
            * Units.map (F : U (K := K) z →* A) (uTm z) ^ g.2 : Aˣ) : A) := by
    intro F
    rw [← map_zpow, ← map_zpow]
    exact map_mul F _ _
  rw [e1 f, e1 d.lift, hp, hm, d.map_uTp, d.map_uTm]


/-- **The universal property of `goalv0a` Definition 1.**  For every commutative `K`-algebra `A`
carrying a presentation datum `d : Data z A`, there is **exactly one** `K`-algebra map
`U z →ₐ[K] A` sending `K_{n,±}` to `d.K_{n,±}`.  Together with `equivTorus` this says that the
Laurent torus used as the model of `U` throughout `sandboxv0a` *is* the algebra presented by
Definition 1, uniquely up to unique isomorphism. -/
theorem existsUnique_lift (d : Data z A) (hz : z ≠ 0) :
    ∃! f : U (K := K) z →ₐ[K] A,
      (∀ n : ℤ, f ((uData z hz).Kplus n) = d.Kplus n) ∧
      (∀ n : ℤ, f ((uData z hz).Kminus n) = d.Kminus n) := by
  refine ⟨d.lift, ⟨d.lift_Kplus hz, d.lift_Kminus hz⟩, ?_⟩
  rintro f ⟨hf1, hf2⟩
  exact d.lift_unique hz f (hf1 1) (hf2 1)

end Universal

/-! ## 11. The model bridge: the delivery's `Torus K` **is** the presented algebra -/

section Model

variable (K)
variable [G : GL2Params K]

/-- The family parameter `z` of `GL2Params` is nonzero (`z = z₁z₂`, both factors nonzero). -/
theorem z_ne_zero : (G.z : K) ≠ 0 := by
  rw [G.z_eq]
  exact mul_ne_zero G.z1_ne_zero G.z2_ne_zero

/-- **The modelling assumption F1 discharged.**  The algebra `NewtonUnivGrid.Torus K` that
`sandboxv0a` uses as its model of `U` is `K`-algebra isomorphic to the algebra presented by
`goalv0a` Definition 1 over the family parameter `z = G.z`, and the isomorphism carries the
presented generators to `K_{n,+} = T^n`, `K_{n,-} = z^n T^{-n}`
(`equivTorus_Kplus`, `equivTorus_Kminus`). -/
noncomputable def modelEquiv : U (K := K) G.z ≃ₐ[K] Torus K :=
  equivTorus G.z (z_ne_zero K)

end Model

end Presentation
end GL1Newton
end A1
end HybridQuantumLean
